# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghrelease" do
  name "ghrelease"
  desc "Fetch and install the latest GitHub release assets automatically"
  homepage "https://github.com/kavishgr/ghrelease"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghrelease"

  on_macos do
    on_intel do
      url "https://github.com/kavishgr/ghrelease/releases/download/v#{version}/ghrelease_darwin_amd64.tar.gz"
      sha256 "7cca603ba63b876fb3d12087b3da5d7eecf4cb66e38b7b4646b7639bfcb42659"
    end
    on_arm do
      url "https://github.com/kavishgr/ghrelease/releases/download/v#{version}/ghrelease_darwin_arm64.tar.gz"
      sha256 "c1184e115a9cd25cb527ab11251ea42e1ecbaef14b0ca11f1c66dc6812bc290c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kavishgr/ghrelease/releases/download/v#{version}/ghrelease_linux_amd64.tar.gz"
      sha256 "33ee28c8e3665429e8690c27043d563c7863530fcb8b93845d9eec5f71aecd0a"
    end
    on_arm do
      url "https://github.com/kavishgr/ghrelease/releases/download/v#{version}/ghrelease_linux_arm64.tar.gz"
      sha256 "97626508bb82550ca90bf431a3dfa46f891ece679dbe7cd707afde69a50f7cbc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghrelease"]
    end
  end

  # No zap stanza required
end
